#!/bin/bash

SHELLSOURCE="/auto_home/todorico/Public/Shell"
SHELLDEST="$HOME/.shell"

rm -r "$SHELLDEST" &> "/dev/null"
cp -r "$SHELLSOURCE" "$SHELLDEST" &> "/dev/null"
make --directory="$SHELLDEST" &> "/dev/null"
chmod -R 777 "$SHELLDEST" &> "/dev/null"

"$SHELLDEST/"./sshell &> "/dev/null"&
